//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajProje.ServiceReference1 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebServiceKatodikSoap")]
    public interface WebServiceKatodikSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<string> HelloWorldAsync();
        
        // CODEGEN: Generating message contract since message SinyalGetirRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SinyalGetir", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        StajProje.ServiceReference1.SinyalGetirResponse SinyalGetir(StajProje.ServiceReference1.SinyalGetirRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SinyalGetir", ReplyAction="*")]
        System.Threading.Tasks.Task<StajProje.ServiceReference1.SinyalGetirResponse> SinyalGetirAsync(StajProje.ServiceReference1.SinyalGetirRequest request);
        
        // CODEGEN: Generating message contract since message SebekeArizaGetirRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SebekeArizaGetir", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        StajProje.ServiceReference1.SebekeArizaGetirResponse SebekeArizaGetir(StajProje.ServiceReference1.SebekeArizaGetirRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SebekeArizaGetir", ReplyAction="*")]
        System.Threading.Tasks.Task<StajProje.ServiceReference1.SebekeArizaGetirResponse> SebekeArizaGetirAsync(StajProje.ServiceReference1.SebekeArizaGetirRequest request);
        
        // CODEGEN: Generating message contract since message TumArizaGetirRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TumArizaGetir", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        StajProje.ServiceReference1.TumArizaGetirResponse TumArizaGetir(StajProje.ServiceReference1.TumArizaGetirRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TumArizaGetir", ReplyAction="*")]
        System.Threading.Tasks.Task<StajProje.ServiceReference1.TumArizaGetirResponse> TumArizaGetirAsync(StajProje.ServiceReference1.TumArizaGetirRequest request);
        
        // CODEGEN: Generating message contract since message KatodikKorumaArizaGetirRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KatodikKorumaArizaGetir", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        StajProje.ServiceReference1.KatodikKorumaArizaGetirResponse KatodikKorumaArizaGetir(StajProje.ServiceReference1.KatodikKorumaArizaGetirRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KatodikKorumaArizaGetir", ReplyAction="*")]
        System.Threading.Tasks.Task<StajProje.ServiceReference1.KatodikKorumaArizaGetirResponse> KatodikKorumaArizaGetirAsync(StajProje.ServiceReference1.KatodikKorumaArizaGetirRequest request);
        
        // CODEGEN: Generating message contract since message ListeGetirRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListeGetir", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        StajProje.ServiceReference1.ListeGetirResponse ListeGetir(StajProje.ServiceReference1.ListeGetirRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListeGetir", ReplyAction="*")]
        System.Threading.Tasks.Task<StajProje.ServiceReference1.ListeGetirResponse> ListeGetirAsync(StajProje.ServiceReference1.ListeGetirRequest request);
        
        // CODEGEN: Generating message contract since message istasyonGetirRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/istasyonGetir", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        StajProje.ServiceReference1.istasyonGetirResponse istasyonGetir(StajProje.ServiceReference1.istasyonGetirRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/istasyonGetir", ReplyAction="*")]
        System.Threading.Tasks.Task<StajProje.ServiceReference1.istasyonGetirResponse> istasyonGetirAsync(StajProje.ServiceReference1.istasyonGetirRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AuthHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string userNameField;
        
        private string passwordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
                this.RaisePropertyChanged("UserName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SinyalGetir", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SinyalGetirRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public StajProje.ServiceReference1.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string parentID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string yil;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string ay;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string gun;
        
        public SinyalGetirRequest() {
        }
        
        public SinyalGetirRequest(StajProje.ServiceReference1.AuthHeader AuthHeader, string parentID, string yil, string ay, string gun) {
            this.AuthHeader = AuthHeader;
            this.parentID = parentID;
            this.yil = yil;
            this.ay = ay;
            this.gun = gun;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SinyalGetirResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SinyalGetirResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Data.DataTable SinyalGetirResult;
        
        public SinyalGetirResponse() {
        }
        
        public SinyalGetirResponse(System.Data.DataTable SinyalGetirResult) {
            this.SinyalGetirResult = SinyalGetirResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SebekeArizaGetir", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SebekeArizaGetirRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public StajProje.ServiceReference1.AuthHeader AuthHeader;
        
        public SebekeArizaGetirRequest() {
        }
        
        public SebekeArizaGetirRequest(StajProje.ServiceReference1.AuthHeader AuthHeader) {
            this.AuthHeader = AuthHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SebekeArizaGetirResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SebekeArizaGetirResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Data.DataTable SebekeArizaGetirResult;
        
        public SebekeArizaGetirResponse() {
        }
        
        public SebekeArizaGetirResponse(System.Data.DataTable SebekeArizaGetirResult) {
            this.SebekeArizaGetirResult = SebekeArizaGetirResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TumArizaGetir", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class TumArizaGetirRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public StajProje.ServiceReference1.AuthHeader AuthHeader;
        
        public TumArizaGetirRequest() {
        }
        
        public TumArizaGetirRequest(StajProje.ServiceReference1.AuthHeader AuthHeader) {
            this.AuthHeader = AuthHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TumArizaGetirResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class TumArizaGetirResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Data.DataTable TumArizaGetirResult;
        
        public TumArizaGetirResponse() {
        }
        
        public TumArizaGetirResponse(System.Data.DataTable TumArizaGetirResult) {
            this.TumArizaGetirResult = TumArizaGetirResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="KatodikKorumaArizaGetir", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class KatodikKorumaArizaGetirRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public StajProje.ServiceReference1.AuthHeader AuthHeader;
        
        public KatodikKorumaArizaGetirRequest() {
        }
        
        public KatodikKorumaArizaGetirRequest(StajProje.ServiceReference1.AuthHeader AuthHeader) {
            this.AuthHeader = AuthHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="KatodikKorumaArizaGetirResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class KatodikKorumaArizaGetirResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Data.DataTable KatodikKorumaArizaGetirResult;
        
        public KatodikKorumaArizaGetirResponse() {
        }
        
        public KatodikKorumaArizaGetirResponse(System.Data.DataTable KatodikKorumaArizaGetirResult) {
            this.KatodikKorumaArizaGetirResult = KatodikKorumaArizaGetirResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListeGetir", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ListeGetirRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public StajProje.ServiceReference1.AuthHeader AuthHeader;
        
        public ListeGetirRequest() {
        }
        
        public ListeGetirRequest(StajProje.ServiceReference1.AuthHeader AuthHeader) {
            this.AuthHeader = AuthHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListeGetirResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ListeGetirResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Data.DataTable ListeGetirResult;
        
        public ListeGetirResponse() {
        }
        
        public ListeGetirResponse(System.Data.DataTable ListeGetirResult) {
            this.ListeGetirResult = ListeGetirResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="istasyonGetir", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class istasyonGetirRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public StajProje.ServiceReference1.AuthHeader AuthHeader;
        
        public istasyonGetirRequest() {
        }
        
        public istasyonGetirRequest(StajProje.ServiceReference1.AuthHeader AuthHeader) {
            this.AuthHeader = AuthHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="istasyonGetirResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class istasyonGetirResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Data.DataTable istasyonGetirResult;
        
        public istasyonGetirResponse() {
        }
        
        public istasyonGetirResponse(System.Data.DataTable istasyonGetirResult) {
            this.istasyonGetirResult = istasyonGetirResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceKatodikSoapChannel : StajProje.ServiceReference1.WebServiceKatodikSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceKatodikSoapClient : System.ServiceModel.ClientBase<StajProje.ServiceReference1.WebServiceKatodikSoap>, StajProje.ServiceReference1.WebServiceKatodikSoap {
        
        public WebServiceKatodikSoapClient() {
        }
        
        public WebServiceKatodikSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceKatodikSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceKatodikSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceKatodikSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public System.Threading.Tasks.Task<string> HelloWorldAsync() {
            return base.Channel.HelloWorldAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StajProje.ServiceReference1.SinyalGetirResponse StajProje.ServiceReference1.WebServiceKatodikSoap.SinyalGetir(StajProje.ServiceReference1.SinyalGetirRequest request) {
            return base.Channel.SinyalGetir(request);
        }
        
        public System.Data.DataTable SinyalGetir(StajProje.ServiceReference1.AuthHeader AuthHeader, string parentID, string yil, string ay, string gun) {
            StajProje.ServiceReference1.SinyalGetirRequest inValue = new StajProje.ServiceReference1.SinyalGetirRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.parentID = parentID;
            inValue.yil = yil;
            inValue.ay = ay;
            inValue.gun = gun;
            StajProje.ServiceReference1.SinyalGetirResponse retVal = ((StajProje.ServiceReference1.WebServiceKatodikSoap)(this)).SinyalGetir(inValue);
            return retVal.SinyalGetirResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StajProje.ServiceReference1.SinyalGetirResponse> StajProje.ServiceReference1.WebServiceKatodikSoap.SinyalGetirAsync(StajProje.ServiceReference1.SinyalGetirRequest request) {
            return base.Channel.SinyalGetirAsync(request);
        }
        
        public System.Threading.Tasks.Task<StajProje.ServiceReference1.SinyalGetirResponse> SinyalGetirAsync(StajProje.ServiceReference1.AuthHeader AuthHeader, string parentID, string yil, string ay, string gun) {
            StajProje.ServiceReference1.SinyalGetirRequest inValue = new StajProje.ServiceReference1.SinyalGetirRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.parentID = parentID;
            inValue.yil = yil;
            inValue.ay = ay;
            inValue.gun = gun;
            return ((StajProje.ServiceReference1.WebServiceKatodikSoap)(this)).SinyalGetirAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StajProje.ServiceReference1.SebekeArizaGetirResponse StajProje.ServiceReference1.WebServiceKatodikSoap.SebekeArizaGetir(StajProje.ServiceReference1.SebekeArizaGetirRequest request) {
            return base.Channel.SebekeArizaGetir(request);
        }
        
        public System.Data.DataTable SebekeArizaGetir(StajProje.ServiceReference1.AuthHeader AuthHeader) {
            StajProje.ServiceReference1.SebekeArizaGetirRequest inValue = new StajProje.ServiceReference1.SebekeArizaGetirRequest();
            inValue.AuthHeader = AuthHeader;
            StajProje.ServiceReference1.SebekeArizaGetirResponse retVal = ((StajProje.ServiceReference1.WebServiceKatodikSoap)(this)).SebekeArizaGetir(inValue);
            return retVal.SebekeArizaGetirResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StajProje.ServiceReference1.SebekeArizaGetirResponse> StajProje.ServiceReference1.WebServiceKatodikSoap.SebekeArizaGetirAsync(StajProje.ServiceReference1.SebekeArizaGetirRequest request) {
            return base.Channel.SebekeArizaGetirAsync(request);
        }
        
        public System.Threading.Tasks.Task<StajProje.ServiceReference1.SebekeArizaGetirResponse> SebekeArizaGetirAsync(StajProje.ServiceReference1.AuthHeader AuthHeader) {
            StajProje.ServiceReference1.SebekeArizaGetirRequest inValue = new StajProje.ServiceReference1.SebekeArizaGetirRequest();
            inValue.AuthHeader = AuthHeader;
            return ((StajProje.ServiceReference1.WebServiceKatodikSoap)(this)).SebekeArizaGetirAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StajProje.ServiceReference1.TumArizaGetirResponse StajProje.ServiceReference1.WebServiceKatodikSoap.TumArizaGetir(StajProje.ServiceReference1.TumArizaGetirRequest request) {
            return base.Channel.TumArizaGetir(request);
        }
        
        public System.Data.DataTable TumArizaGetir(StajProje.ServiceReference1.AuthHeader AuthHeader) {
            StajProje.ServiceReference1.TumArizaGetirRequest inValue = new StajProje.ServiceReference1.TumArizaGetirRequest();
            inValue.AuthHeader = AuthHeader;
            StajProje.ServiceReference1.TumArizaGetirResponse retVal = ((StajProje.ServiceReference1.WebServiceKatodikSoap)(this)).TumArizaGetir(inValue);
            return retVal.TumArizaGetirResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StajProje.ServiceReference1.TumArizaGetirResponse> StajProje.ServiceReference1.WebServiceKatodikSoap.TumArizaGetirAsync(StajProje.ServiceReference1.TumArizaGetirRequest request) {
            return base.Channel.TumArizaGetirAsync(request);
        }
        
        public System.Threading.Tasks.Task<StajProje.ServiceReference1.TumArizaGetirResponse> TumArizaGetirAsync(StajProje.ServiceReference1.AuthHeader AuthHeader) {
            StajProje.ServiceReference1.TumArizaGetirRequest inValue = new StajProje.ServiceReference1.TumArizaGetirRequest();
            inValue.AuthHeader = AuthHeader;
            return ((StajProje.ServiceReference1.WebServiceKatodikSoap)(this)).TumArizaGetirAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StajProje.ServiceReference1.KatodikKorumaArizaGetirResponse StajProje.ServiceReference1.WebServiceKatodikSoap.KatodikKorumaArizaGetir(StajProje.ServiceReference1.KatodikKorumaArizaGetirRequest request) {
            return base.Channel.KatodikKorumaArizaGetir(request);
        }
        
        public System.Data.DataTable KatodikKorumaArizaGetir(StajProje.ServiceReference1.AuthHeader AuthHeader) {
            StajProje.ServiceReference1.KatodikKorumaArizaGetirRequest inValue = new StajProje.ServiceReference1.KatodikKorumaArizaGetirRequest();
            inValue.AuthHeader = AuthHeader;
            StajProje.ServiceReference1.KatodikKorumaArizaGetirResponse retVal = ((StajProje.ServiceReference1.WebServiceKatodikSoap)(this)).KatodikKorumaArizaGetir(inValue);
            return retVal.KatodikKorumaArizaGetirResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StajProje.ServiceReference1.KatodikKorumaArizaGetirResponse> StajProje.ServiceReference1.WebServiceKatodikSoap.KatodikKorumaArizaGetirAsync(StajProje.ServiceReference1.KatodikKorumaArizaGetirRequest request) {
            return base.Channel.KatodikKorumaArizaGetirAsync(request);
        }
        
        public System.Threading.Tasks.Task<StajProje.ServiceReference1.KatodikKorumaArizaGetirResponse> KatodikKorumaArizaGetirAsync(StajProje.ServiceReference1.AuthHeader AuthHeader) {
            StajProje.ServiceReference1.KatodikKorumaArizaGetirRequest inValue = new StajProje.ServiceReference1.KatodikKorumaArizaGetirRequest();
            inValue.AuthHeader = AuthHeader;
            return ((StajProje.ServiceReference1.WebServiceKatodikSoap)(this)).KatodikKorumaArizaGetirAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StajProje.ServiceReference1.ListeGetirResponse StajProje.ServiceReference1.WebServiceKatodikSoap.ListeGetir(StajProje.ServiceReference1.ListeGetirRequest request) {
            return base.Channel.ListeGetir(request);
        }
        
        public System.Data.DataTable ListeGetir(StajProje.ServiceReference1.AuthHeader AuthHeader) {
            StajProje.ServiceReference1.ListeGetirRequest inValue = new StajProje.ServiceReference1.ListeGetirRequest();
            inValue.AuthHeader = AuthHeader;
            StajProje.ServiceReference1.ListeGetirResponse retVal = ((StajProje.ServiceReference1.WebServiceKatodikSoap)(this)).ListeGetir(inValue);
            return retVal.ListeGetirResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StajProje.ServiceReference1.ListeGetirResponse> StajProje.ServiceReference1.WebServiceKatodikSoap.ListeGetirAsync(StajProje.ServiceReference1.ListeGetirRequest request) {
            return base.Channel.ListeGetirAsync(request);
        }
        
        public System.Threading.Tasks.Task<StajProje.ServiceReference1.ListeGetirResponse> ListeGetirAsync(StajProje.ServiceReference1.AuthHeader AuthHeader) {
            StajProje.ServiceReference1.ListeGetirRequest inValue = new StajProje.ServiceReference1.ListeGetirRequest();
            inValue.AuthHeader = AuthHeader;
            return ((StajProje.ServiceReference1.WebServiceKatodikSoap)(this)).ListeGetirAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StajProje.ServiceReference1.istasyonGetirResponse StajProje.ServiceReference1.WebServiceKatodikSoap.istasyonGetir(StajProje.ServiceReference1.istasyonGetirRequest request) {
            return base.Channel.istasyonGetir(request);
        }
        
        public System.Data.DataTable istasyonGetir(StajProje.ServiceReference1.AuthHeader AuthHeader) {
            StajProje.ServiceReference1.istasyonGetirRequest inValue = new StajProje.ServiceReference1.istasyonGetirRequest();
            inValue.AuthHeader = AuthHeader;
            StajProje.ServiceReference1.istasyonGetirResponse retVal = ((StajProje.ServiceReference1.WebServiceKatodikSoap)(this)).istasyonGetir(inValue);
            return retVal.istasyonGetirResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StajProje.ServiceReference1.istasyonGetirResponse> StajProje.ServiceReference1.WebServiceKatodikSoap.istasyonGetirAsync(StajProje.ServiceReference1.istasyonGetirRequest request) {
            return base.Channel.istasyonGetirAsync(request);
        }
        
        public System.Threading.Tasks.Task<StajProje.ServiceReference1.istasyonGetirResponse> istasyonGetirAsync(StajProje.ServiceReference1.AuthHeader AuthHeader) {
            StajProje.ServiceReference1.istasyonGetirRequest inValue = new StajProje.ServiceReference1.istasyonGetirRequest();
            inValue.AuthHeader = AuthHeader;
            return ((StajProje.ServiceReference1.WebServiceKatodikSoap)(this)).istasyonGetirAsync(inValue);
        }
    }
}
